### ISSUE TITLE
Relationship with isosurfaces

### ISSUE THREAD

**Issue by stla** [coolbutuseless/isocubes#4]
Hello,

I think the documentation could mention that an isocubes object is similar to an isosurface. Here is a couple of examples I did, based on some isosurface equations.

![isocubes_BarthSextic](https://github.com/coolbutuseless/isocubes/assets/4466543/4d5108ac-f74f-4c54-b35d-e3fc4c49322f)

![isocubes_Enzensberger](https://github.com/coolbutuseless/isocubes/assets/4466543/e3eafbf1-6b6f-4ded-b701-cb8cac3a6145)

![isocubes_SolidMoebiusStrip](https://github.com/coolbutuseless/isocubes/assets/4466543/28b55d02-de4f-473e-ac57-7092732ede7f)

![isocubes_spiderCage](https://github.com/coolbutuseless/isocubes/assets/4466543/ac8e6854-001d-4ade-8fe9-1006b0cc103f)

**Comment by coolbutuseless** [comment]
Good point!

These are great visualisations.   I plan to include some isosurface examples with the upcoming release.
